apiVersion: v1
kind: Namespace
metadata:
  name: prepull
---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: prepull
  namespace: prepull
spec:
  selector:
    matchLabels:
      name: prepull
  template:
    metadata:
      labels:
        name: prepull
    spec:
      terminationGracePeriodSeconds: 5
      initContainers:
      - name: prepull
        image: gcr.io/nimble-valve-236407/cms-higgs-4l-full
        command: ["bash", "-c", "echo", "1"]
      - name: prepull-worker
        image: gcr.io/nimble-valve-236407/worker
        command: ["bash", "-c", "echo", "1"]
      containers:
      - name: pause
        image: gcr.io/google_containers/pause
