apiVersion: batch/v1
kind: Job
metadata:
  name: $jobname
  namespace: $namespace
spec:
  template:
    spec:
      terminationGracePeriodSeconds: 5
      shareProcessNamespace: true
      initContainers:
      - name: prepull
        image: gcr.io/nimble-valve-236407/worker
        command: [ "bash", "-c", "/getfile.sh" ]
        env:
          - name: CMS_INPUT_FILES
            value: $eventfile
          - name: GCS_ACCESS
            value: $gs_access_key
          - name: GCS_SECRET
            value: $gs_secret_key
          - name: GCS_HOST
            value: $gs_host
          - name: GCS_PROJECT_ID
            value: $gs_project_id
          - name: DOWNLOAD_MAX_KB
            value: "$download_max_kb"
          - name: UPLOAD_MAX_KB
            value: "$upload_max_kb"
          - name: DPATH
            value: "$dpath"
        resources:
          requests:
            cpu: 0.9
            memory: 6Gi
          limits:
            cpu: 0.9
            memory: 6Gi
        volumeMounts:
          - mountPath: /getfile.sh
            subPath: getfile.sh
            name: getfile
          - mountPath: /inputs
            name: inputs
      containers:
      - name: cmsrun
        image: $image
        command: [ "bash", "-c", "/runjob.sh" ]
        env:
          - name: CMS_LUMINOSITY_DATA
            value: '$lumi_data'
          - name: CMS_JSON
            value: $jsonfile
          - name: CMS_INPUT_FILES
            value: $eventfile
          - name: CMS_OUTPUT_FILE
            value: $output_file
          - name: CMS_OUTPUT_JSON_FILE
            value: $output_json_file
          - name: CMS_S3_BASEDIR
            value: $s3_basedir
          - name: CMS_OUTPUT_S3PATH
            value: $s3_outputpath
          - name: CMS_CONFIG
            value: $config
          - name: CMS_DATASET_NAME
            value: $fullsetname
          - name: MC_MULTIPART_THREADS
            value: "$multipart_threads"
          - name: S3_ACCESS
            value: $s3_access_key
          - name: S3_SECRET
            value: $s3_secret_key
          - name: S3_HOST
            value: $s3_host
          - name: GCS_ACCESS
            value: $gs_access_key
          - name: GCS_SECRET
            value: $gs_secret_key
          - name: GCS_HOST
            value: $gs_host
          - name: GCS_PROJECT_ID
            value: $gs_project_id
          - name: DOWNLOAD_MAX_KB
            value: "$download_max_kb"
          - name: UPLOAD_MAX_KB
            value: "$upload_max_kb"
          - name: REDIS_HOST
            value: $redis_host
          - name: DPATH
            value: "$dpath"
        resources:
          requests:
            cpu: 0.9
            memory: 6Gi
          limits:
            cpu: 0.9
            memory: 6Gi
        volumeMounts:
          - mountPath: /runjob.sh
            subPath: runjob.sh
            name: runjob
          - mountPath: /inputs
            name: inputs
      restartPolicy: Never
      volumes:
      - name: runjob
        configMap:
          name: runjob
          defaultMode: 0755
      - name: getfile
        configMap:
          name: getfile
          defaultMode: 0755
      - name: inputs
        emptyDir:
          medium: Memory
          #- name: inputs
          #  hostPath:
          #    path: "$dpath"
          #    type: $ftype
  backoffLimit: $backoff_limit
  completions: 1
  parallelism: 1
