apiVersion: batch/v1
kind: Job
metadata:
  name: $jobname
  namespace: $namespace
spec:
  template:
    spec:
      containers:
      - name: cmsrun
        image: $image
        command: [ "bash", "-c", "/runjob.sh" ]
        env:
          - name: CMS_JSON
            value: $jsonfile
          - name: CMS_INPUT_FILES
            value: $eventfile
          - name: CMS_OUTPUT_FILE
            value: $output_file
          - name: CMS_OUTPUT_JSON_FILE
            value: $output_json_file
          - name: CMS_LUMINOSITY_DATA
            value: '$lumi_data'
          - name: CMS_S3_BASEDIR
            value: $s3_basedir
          - name: CMS_OUTPUT_S3PATH
            value: $s3_outputpath
          - name: CMS_CONFIG
            value: $config
          - name: CMS_DATASET_NAME
            value: $datasetname
          - name: MC_MULTIPART_THREADS
            value: "$multipart_threads"
          - name: S3_ACCESS
            value: $s3_access_key
          - name: S3_SECRET
            value: $s3_secret_key
          - name: S3_HOST
            value: $s3_host
          - name: GCS_ACCESS
            value: $gs_access_key
          - name: GCS_SECRET
            value: $gs_secret_key
          - name: GCS_HOST
            value: $gs_host
        resources:
          requests:
            cpu: $cpu_limit
          limits:
            cpu: $cpu_limit
        volumeMounts:
          - mountPath: /runjob.sh
            subPath: runjob.sh
            name: runjob
      restartPolicy: Never
      volumes:
      - name: runjob
        configMap:
          name: runjob
          defaultMode: 0755
  backoffLimit: $backoff_limit
  completions: 1
  parallelism: 1
